# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Main branch pull request checks

on:
  pull_request:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup node v${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:ci

  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup node v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check linting
      run: npm run lint

  e2e:
    runs-on: ${{ matrix.os }}
    environment: ci

    strategy:
      matrix:
        browser: [chrome, edge, firefox]
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-10, windows-latest]
        include:
          - os: macos-latest
            node-version: 18
            browser: safari

    steps:
    - uses: actions/checkout@v3

    - name: Setup node v${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Build source
      run: npm run build
    
    - name: Start up server
      run: npm run serve:ci
    
    - name: Run e2e tests
      run: npm run cy:run -- --record --key $CYPRESS_CLOUD_KEY --browser ${{ matrix.browser }}
